aoi: data/aoi.gpkg
hex_res: 5
raster_like: data/blank_proj.tif

features:
  - name: pop
    type: raster
    file: data/hrsl.tif
    operation: sum
    decimals: 0
    fix:
      minimum: 0

  - name: precip
    type: raster
    file: data/precip.tif
    operation: mean
    decimals: 0
    fix:
      minimum: 0

  - name: grid_dist
    type: vector
    operation: distance
    file: data/grid.gpkg
    decimals: 2
    fix:
      factor: 0.001

  - name: lake_dist
    type: vector
    operation: distance
    file: data/victoria.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: water_dist
    type: vector
    operation: distance
    file: data/lakes.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: river_dist
    type: vector
    operation: distance
    file: data/rivers.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: road_dist
    type: vector
    operation: distance
    file: data/roads.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: urban_dist
    type: vector
    operation: distance
    file: data/towns.gpkg
    decimals: 3
    fix:
      factor: 0.001

  - name: city_dist
    type: vector
    operation: distance
    file: data/cities.gpkg
    decimals: 3
    fix:
      factor: 0.001
